### ISSUE TITLE
Error on start

### ISSUE THREAD

**Issue by tocks53** [XanderStrike/ApolloUI#20]
Hello, when i run the program. I have this traceback.
I am on Ubuntu

beber@beber-Portable:~/Téléchargements/ApolloUI-master$ ls
ApolloUI.py  assets  lib  readme.md  templates  torrents  wsgi.py
beber@beber-Portable:~/Téléchargements/ApolloUI-master$ python ApolloUI.py
Traceback (most recent call last):
  File "ApolloUI.py", line 13, in <module>
    import lib.wat as wat
  File "/home/beber/Téléchargements/ApolloUI-master/lib/wat.py", line 1, in <module>
    import whatapi
  File "/home/beber/Téléchargements/ApolloUI-master/lib/whatapi/__init__.py", line 1, in <module>
    from .whatapi import WhatAPI
  File "/home/beber/Téléchargements/ApolloUI-master/lib/whatapi/whatapi.py", line 5, in <module>
    import requests
ImportError: No module named requests

**Comment by XanderStrike** [comment]
`pip install requests` should solve this I think. Let me know if it does and I'll add it to the readmen.

**Comment by XanderStrike** [comment]
Closing because it sounds like this has solved other people's issues.
